### ISSUE TITLE
pretty_printing.ml error on master

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stanc3#290]
Not sure if just my machine but I'm getting the below on master when doing `dune runtest`

```
File "src/frontend/Pretty_printing.ml", line 77, characters 41-55:
Error: This expression has type
         Middle.unsizedtype Fmt.t =
           Format.formatter -> Middle.unsizedtype -> unit
       but an expression was expected of type
         Middle.autodifftype Fmt.t =
           Format.formatter -> Middle.autodifftype -> unit
       Type Middle.unsizedtype is not compatible with type
         Middle.autodifftype 
```

Build info below, if no one else is getting this error then it's prob just my computer doing something wonky

```
dune external-lib-deps ./ --build-info
version: 1.11.3
statically linked libraries:
- catapult           n/a
- cmdliner           n/a
- dag                n/a
- dune               n/a
- dune-build-info    1.11.3
- dune._caml         1.11.3
- dune._dune_lang    1.11.3
- dune._ocaml_config 1.11.3
- dune._result       1.11.3
- dune._stdune       1.11.3
- dune._wp.dune      1.11.3
- dune_re            n/a
- fiber              n/a
- incremental_cycles n/a
- main               n/a
- memo               n/a
- opam_file_format   n/a
- threads.posix      [distributed with Ocaml]
- unix               [distributed with Ocaml]
- xdg                n/a
```

**Comment by seantalts** [comment]
what command are you running? I think master should be working... try dune
clean?

**Comment by SteveBronder** [comment]
Nah after `dune clean` I'm still getting the following

```
$ dune clean
$ dune runtest
      menhir src/frontend/parsing_errors.ml
Read 455 sample input sentences and 455 error messages.
File "src/frontend/Pretty_printing.ml", line 77, characters 41-55:
Error: This expression has type
         Middle.unsizedtype Fmt.t =
           Format.formatter -> Middle.unsizedtype -> unit
       but an expression was expected of type
         Middle.autodifftype Fmt.t =
           Format.formatter -> Middle.autodifftype -> unit
       Type Middle.unsizedtype is not compatible with type
         Middle.autodifftype 
```

What do I run to get the dependency versions?

**Comment by SteveBronder** [comment]
The function is 
```ocaml
and pp_argtype ppf = function
  | at, ut -> Fmt.append pp_autodifftype pp_unsizedtype ppf (at, ut)
```

and it's used here right above on line 70

```ocaml
and pp_unsizedtype ppf = function
  | Middle.UInt -> Fmt.pf ppf "int"
  | Middle.UReal -> Fmt.pf ppf "real"
  | Middle.UVector -> Fmt.pf ppf "vector"
  | Middle.URowVector -> Fmt.pf ppf "row_vector"
  | Middle.UMatrix -> Fmt.pf ppf "matrix"
  | Middle.UArray ut ->
      let ut2, d = unwind_array_type ut in
      let array_str = "[" ^ String.make d ',' ^ "]" in
      Fmt.(suffix (const string array_str) pp_unsizedtype ppf ut2)
  | Middle.UFun (argtypes, rt) ->
      Fmt.pf ppf "{|@[<h>(%a) => %a@]|}"
        Fmt.(list ~sep:comma_no_break pp_argtype)
        argtypes pp_returntype rt
  | Middle.UMathLibraryFunction -> Fmt.pf ppf "Stan Math function"
```

**Comment by seantalts** [comment]
you should be able to run scripts/install_build_deps.sh and scripts/install_dev_deps.sh to get the right versions of stuff. I'm not sure this is a versioning thing...

**Comment by seantalts** [comment]
This is with master completely clean and no extra files?

**Comment by SteveBronder** [comment]
I'm gonna try to just delete the repo and clone it tmrw

**Comment by seantalts** [comment]
You can also use git reset --hard HEAD
And
git clean -xffd
 Together.

Very confusing error!

**Comment by SteveBronder** [comment]
Odd! Ended up being something with my dependencies. Moving down to the dune version (10 something) from the install_dep bash script did the trick
